# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The purpose of this CI job is to check that cuOpt.jl can be loaded without
# cuOpt installed when JULIA_REGISTRYCI_AUTOMERGE is set to `true`.
#
# This is required so that the JuliaRegistry will automatically merge our
# releases without manual intervention.
#
# This job can be removed when we support automatic installation of cuOpt in the
# future.
name: Check-Registry-CI-Automerge
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
jobs:
  test:
    name: Check Registry CI Automerge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          arch: 'x86'
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - run: julia --color=yes --project=. -e 'using cuOpt'
        env:
          JULIA_REGISTRYCI_AUTOMERGE: true
